k0shk0sh/FastHub

app/build.gradle, build.gradle
Reverts k0shk0sh/FastHub#119
Reverting this commit hence it causes butterknife to stop binding views.
=> Revert "annotationProcessor instead of neenbedankt.android-apt"

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/com/fastaccess/ui/modules/about/FastHubAboutActivity.java, app/src/main/res/values/colors.xml, app/src/main/res/values/styles.xml
You might want to add more or less information about yourself.
=> Created simple MaterialAboutActivity

app/src/main/java/com/fastaccess/data/LoginRestService.java, app/src/main/java/com/fastaccess/data/dao/AuthModel.java, app/src/main/java/com/fastaccess/data/service/UserRestService.java, app/src/main/java/com/fastaccess/provider/rest/LoginProvider.java, app/src/main/java/com/fastaccess/provider/rest/RestProvider.java, app/src/main/java/com/fastaccess/ui/modules/login/LoginMvp.java, app/src/main/java/com/fastaccess/ui/modules/login/LoginPresenter.java, app/src/main/java/com/fastaccess/ui/modules/login/LoginView.java, app/src/main/res/layouts/main_layouts/layout/login_layout.xml, app/src/main/res/values/strings.xml
Hi @k0shk0sh 
I've implemented the OTP (2fa) code.
But now i encountered a problem with the token, maybe you can take a look on it:
https://developer.github.com/changes/2014-12-08-removing-authorizations-token/
> I've updated the login card color, now uses `colorAccent` and is more visual :P
=> Add OTP code

app/build.gradle, app/src/main/java/com/fastaccess/App.java
There is no need for support multidex, as minsdk is set to 21+
=> multidex is built-in for sdk 21+

README.md
=> README: no jobdispatcher anymore

app/build.gradle, app/src/main/java/com/fastaccess/helper/GithubConfigHelper.java, app/src/main/java/com/fastaccess/ui/modules/login/LoginPresenter.java, debug_gradle.properties
final one for f-droid, and the redirect url in general
=> rework keys, urls

app/build.gradle, build.gradle
add conditionals for dependencies, so that we don't have to patch the file on f-droid
=> fixes for f-droid, 1.8.2 re-release

app/src/main/res/values-de/strings.xml
Translated all the strings to german
=> Language: Strings translated

CONTRIBUTE.md
Just a few mistakes I came upon while reading the contribution guide.
=> Minor spelling mistakes fixes

README.md
This is just a small typo fix.
=> Fix MatrialTapTargetPrompt typo

app/src/main/java/com/fastaccess/ui/widgets/StateLayout.java
=> Revert "use boolean to show reload instead of int"

app/src/main/java/com/fastaccess/ui/widgets/StateLayout.java
fixed initial state
tests were good
=> fixed PR "use boolean to show reload instead of int"

app/src/main/res/values-de/strings.xml
Updated the strings.xml with the new strings
=> Translated new strings to german

app/src/main/res/values-it/strings.xml, app/src/main/res/values/arrays.xml
- Added **Italian** localization (values-it/strings.xml)
- Added items for Italian localization inside arrays.xml
=> Add Italian localization

app/build.gradle, app/src/fdroid/java/com/fastaccess/ui/base/AdActivity.java, app/src/main/java/com/fastaccess/App.java, app/src/main/java/com/fastaccess/provider/tasks/git/GithubActionService.java, app/src/main/java/com/fastaccess/ui/base/BaseActivity.java, app/src/main/java/com/fastaccess/ui/modules/login/LoginActivity.java, app/src/main/java/com/fastaccess/ui/modules/login/LoginMvp.java, app/src/main/java/com/fastaccess/ui/modules/login/LoginPresenter.java, app/src/main/res/layouts/main_layouts/layout-v26/login_form_layout.xml, app/src/main/res/layouts/main_layouts/layout/login_form_layout.xml, app/src/main/res/menu/drawer_menu.xml, app/src/main/res/values/strings.xml
* Fix Issue #512 - Previously starring was "staring".
* Remove "Gists" section - Previously, were the actions were, "Gists" was now the label. [ Private Issue ]
* Add Android O Autofill support.
* Add Google Smart Lock - Logging you in automatically assuming you've logged in before. ( In this commit )
=> Fix #512, Add Google Smart Lock, Android O Autofill, Fix Bug.

app/src/main/AndroidManifest.xml, app/src/main/java/com/fastaccess/ui/modules/profile/overview/ProfileOverviewFragment.java, app/src/main/java/com/fastaccess/ui/modules/profile/overview/ProfileOverviewMvp.java, app/src/main/java/com/fastaccess/ui/modules/profile/overview/ProfileOverviewPresenter.java, app/src/main/res/layouts/row_layouts/layout/profile_overview_layout.xml, app/src/main/res/values/themes.xml
* Previously BannerInfoActivity wouldn't run, now it does.
* If you had more than one gist ( Specifically one before the header, but on the first page. ), your header would not show up. This fixes that.
* Small UI Changes
=> Bug Fixes.

app/src/main/java/com/fastaccess/data/dao/model/FilterOptionsModel.java, app/src/main/java/com/fastaccess/data/service/OrganizationService.java, app/src/main/java/com/fastaccess/ui/modules/profile/org/repos/OrgReposFragment.java, app/src/main/java/com/fastaccess/ui/modules/profile/org/repos/OrgReposMvp.java, app/src/main/java/com/fastaccess/ui/modules/profile/org/repos/OrgReposPresenter.java, app/src/main/java/com/fastaccess/ui/modules/profile/repos/ProfileReposFilterBottomSheetDialog.java, app/src/main/java/com/fastaccess/ui/modules/profile/repos/ProfileReposPresenter.java, app/src/main/java/com/fastaccess/ui/modules/user/UserPagerActivity.java, app/src/main/res/layouts/main_layouts/layout/filter_bottom_sheet.xml
- Fix crash in Organization repo page
- Add listeners to Organization repo fragment
- Disable sorting for Organization repo
Completes #167
=> Add filter to organization repo page

app/src/main/res/values-lt/strings.xml
Just this one single string. Hopefully I did not mess up anything since I am doing this on my phone! 👍
=> Translate Premium Theme string to Lithuanian

app/src/main/res/values-pt-rBR/strings.xml
Translation to brazilian portuguese, pull request now fixed and updated
=> Translation to Brazilian Portuguese

app/src/main/res/values/arrays.xml
Added the Brazilian Portuguese to 2 language arrays
=> Included pt-br on languages arrays

README.md
Don't worry if you feel like it's too minor of a library to include - I don't mind.
=> Added material-about-library to README.md

app/src/main/res/values-pt-rBR/strings.xml
=> Fixed Translation Typos

appveyor.yml
=> Improved artifacts deployment

README.md, app/build.gradle, app/src/main/java/com/fastaccess/ui/modules/repos/issues/create/CreateIssueActivity.java
If there is a will there is a way
=> My first attempt to add an info dialog

app/src/main/java/com/fastaccess/helper/ActivityHelper.java
This is related to issue #705 .
=> Use text/plain MIME Type in share URL intent

app/src/main/java/com/fastaccess/helper/AppHelper.java
do to #712 I have made this change.
=> Emulator detection

app/src/main/java/com/fastaccess/data/dao/types/IssueEventType.java, app/src/main/java/com/fastaccess/provider/timeline/TimelineProvider.java, app/src/main/java/com/fastaccess/ui/adapter/viewholder/FeedsViewHolder.java, app/src/main/java/com/fastaccess/ui/modules/main/orgs/OrgListDialogFragment.java, app/src/main/res/values/strings.xml
@k0shk0sh I am making this pull request to test something out. Dont merge.
=> New grammer items (dont merge!)

app/src/main/java/com/fastaccess/provider/timeline/HtmlHelper.java, app/src/main/java/com/fastaccess/provider/timeline/handler/BetterLinkMovementExtended.java, app/src/main/res/menu/link_popup_menu.xml, app/src/main/res/values/strings.xml
=> Long press a link to copy it, open it, or open it in a new window

app/src/main/res/layouts/main_layouts/layout/login_form_layout.xml
Seems to be more suiting since its always a number code
=> Change two factor input to number input type instead of text

app/src/main/java/com/fastaccess/ui/base/MainNavDrawer.kt, app/src/main/java/com/fastaccess/ui/modules/pinned/PinnedReposFragment.java, app/src/main/res/layouts/other_layouts/layout/nav_menu_layout.xml
@k0shk0sh don't kill me.... This is what I mean....
=> Removed the drop down and made the pinned load pinned :)

app/src/main/res/values/arrays.xml
Chinese(Simplified) -> 简体中文
Chinese(Traditional) -> 正體中文
Japan -> 日本語
...
=> localize language name list

app/src/main/res/values/arrays.xml
=> fix typo of "Русский"

appveyor.yml
=> Downgraded C# Script version

app/src/main/java/com/fastaccess/helper/AppHelper.java, app/src/main/res/values/strings.xml
adds a notice if the land is not english that request ahould be in english
=> fixes #787

app/src/main/res/values-zh-rTW/strings.xml
=> update zh-rTW translation

app/src/main/res/values-zh-rTW/strings.xml
sorry... I forgot that in previous pull request
=> zh-rTW english_please string translation

app/build.gradle, app/src/main/java/com/fastaccess/App.java, app/src/main/java/com/fastaccess/helper/AppHelper.java, app/src/main/java/com/fastaccess/helper/DeviceNameGetter.java, app/src/main/java/com/fastaccess/helper/PrefGetter.java
_Sent from my Nexus 9 using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
=> Changed sig to use jaredrummler/AndroidDeviceNames lib

app/src/main/res/values-ru/strings.xml, app/src/main/res/values/strings.xml
Menu elements now have a simplified names.  
Requesting reviews from @k0shk0sh and @yakov116.
=> Improved default translation

app/build.gradle, build.gradle
Signed-off-by: Yakov <yakov116@gmail.com>
=> Fix error 206

app/src/main/assets/colors.json
see:
- https://github.com/github/linguist/commit/6f0d801375d86cbeb4782b2ccfc1d54608805a54
- https://github.com/github/linguist/commit/b94e018c3af1ca5b3858f2249253d076b26df6a0
=> Update color of Fantom and Haskell

app/src/main/java/com/fastaccess/ui/modules/repos/code/prettifier/ViewerFragment.java
fixed #858 fixed #833 and fixed #863
=> fixed #833

README.md
GFM (and Markdown in general AFAIK) doesn't support writing markdown inside HTML markup.
=> Fix Language Contributors links in README

app/src/main/res/values-ru/strings.xml
It would be better to merge this Pull Request right before the release so the translation will be up-to-date.
=> Improved Russian translation

app/src/main/res/values-pt-rBR/strings.xml
Sorry, I'm late, I was traslating other things too =D
=> Updated ptBR translation

app/src/main/res/values-ko/strings.xml
Worked in some translations that weren't finished.
`Banner` translation not done yet.
=> Added unfinished Korean translations

app/src/main/java/com/fastaccess/data/dao/GitCommitModel.java
This commit changes the commit hash in the commit chooser dialog on the feeds section to show commit message along with the commit hash.
=> show commit message with hash on commit chooser dialog.

README.md
=> Changed "Orgs" to "Organisation"

app/src/main/res/values/strings.xml
Possible newline typo, not sure
=> Possible newline typo

app/src/main/java/com/fastaccess/provider/markdown/CachedComments.kt, app/src/main/java/com/fastaccess/ui/adapter/viewholder/PullRequestEventViewHolder.kt, app/src/main/java/com/fastaccess/ui/adapter/viewholder/UnknownTypeViewHolder.kt, app/src/main/java/com/fastaccess/ui/base/MainNavDrawer.kt, app/src/main/java/com/fastaccess/ui/modules/editor/emoji/EmojiBottomSheet.kt, app/src/main/java/com/fastaccess/ui/modules/main/donation/CheckPurchaseActivity.kt, app/src/main/java/com/fastaccess/ui/modules/repos/extras/branches/BranchesFragment.kt, app/src/main/java/com/fastaccess/ui/modules/repos/extras/branches/pager/BranchesPagerFragment.kt, app/src/main/java/com/fastaccess/ui/modules/repos/git/delete/DeleteFileBottomSheetFragment.kt, app/src/main/java/com/fastaccess/ui/modules/repos/projects/RepoProjectsFragmentPager.kt, app/src/main/java/com/fastaccess/ui/modules/repos/projects/columns/ProjectColumnFragment.kt, app/src/main/java/com/fastaccess/ui/modules/reviews/changes/ReviewChangesActivity.kt, app/src/main/java/com/fastaccess/ui/modules/settings/sound/NotificationSoundBottomSheet.kt, app/src/main/java/com/fastaccess/ui/modules/trending/TrendingActivity.kt, build.gradle, gradle/wrapper/gradle-wrapper.properties
=> Kotlin things

README.md
Newline looked ugly
(I suck at Markdown.)
=> Update README.md (Newline Issue Again, Header Size Inconsistency)

.travis.yml, app/src/main/res/values/strings.xml
=> Updated FAQ

.travis.yml
4 min 29 sec against 7 min 10 sec.
=> Speeded up Travis CI

app/build.gradle, build.gradle, gradle/wrapper/gradle-wrapper.properties
Had some fun :) I tested them all
=> Libs Update

app/src/main/res/values-tr/strings.xml
It was a bit out of date I think, 3 months?
Also checked previous translation, couldn't see any errors.
=> Updated Turkish Translation

app/src/main/res/raw/changelog.html
Fixed English expression in the permanent bit of changelog
=> Improve Changelog Expression

app/src/main/AndroidManifest.xml, app/src/main/java/com/fastaccess/helper/AppHelper.java, app/src/main/java/com/fastaccess/ui/modules/main/premium/PremiumPresenter.kt, app/src/main/java/com/fastaccess/ui/modules/profile/ProfilePagerFragment.java, app/src/main/java/com/fastaccess/ui/modules/profile/org/repos/OrgReposFragment.java, app/src/main/java/com/fastaccess/ui/modules/profile/repos/ProfileReposFilterBottomSheetDialog.java, app/src/main/java/com/fastaccess/ui/modules/profile/repos/ProfileReposFragment.java, app/src/main/java/com/fastaccess/ui/modules/search/SearchPresenter.java, app/src/main/java/com/fastaccess/ui/modules/search/SearchUserActivity.kt, app/src/main/java/com/fastaccess/ui/modules/user/UserPagerActivity.java, app/src/main/res/layout/activity_search_user.xml, app/src/main/res/layouts/main_layouts/layout/filter_bottom_sheet.xml, app/src/main/res/values/strings.xml
=> Search repos and fixes #1111

app/src/main/res/values-de/strings.xml
**All missing strings** were now translated to **german**.
=> Language: German Strings translated

app/src/main/res/values/strings.xml
This is regarding issue #1309.
=> More descriptive search warning

app/src/main/java/com/fastaccess/ui/modules/main/pullrequests/MyPullRequestFragment.java, app/src/main/java/com/fastaccess/ui/modules/pinned/pullrequest/PinnedPullRequestFragment.java, app/src/main/java/com/fastaccess/ui/modules/repos/issues/issue/RepoClosedIssuesFragment.java, app/src/main/java/com/fastaccess/ui/modules/repos/issues/issue/RepoOpenedIssuesFragment.java, app/src/main/java/com/fastaccess/ui/modules/repos/pull_requests/pull_request/RepoPullRequestFragment.java, app/src/main/res/values-bg/strings.xml, app/src/main/res/values-cs/strings.xml, app/src/main/res/values-de/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-in/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values-ja/strings.xml, app/src/main/res/values-ko/strings.xml, app/src/main/res/values-lt/strings.xml, app/src/main/res/values-pl/strings.xml, app/src/main/res/values-pt-rBR/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values-tr/strings.xml, app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values-zh-rTW/strings.xml, app/src/main/res/values/arrays.xml, app/src/main/res/values/strings.xml
Please let me know which of above can be accepted.
=> Polish: strings translated

README.md
- Files: README.md
- Changes: GPLv3 Badge Added
=> [README] GPLv3 Badge Added

app/src/main/res/values-de/strings.xml
=> Updated German lang

app/src/main/res/values/strings.xml
Change `User unlocked` to `User unblocked`
=> Fix spelling error

app/src/main/res/values-de/strings.xml
I corrected a few typos and fixed the FAQ
=> Corrected translation

app/src/main/java/com/fastaccess/ui/base/BaseActivity.java
The press once again toast is now themed according to the current theme as mentioned in issue #1497.
=> fixed the toast theme bug in issue #1497

app/src/main/res/values-ja/strings.xml
Hi.
Japanese Translation is not updated from 2 months ago.
During this term, there are a lot of changes in strings.xml.
Now, I reflected these changes in values-ja/strings.xml.
P.S.
I think FastHub is the best ever GitHub client for Android.
This was the reason why I contributed this project.
Thank you for maintain!
=> Language: Added Japanese strings

app/src/main/res/values-de/strings.xml
=> Fix #1548 (german translation error)

app/src/main/res/values-es/strings.xml
inlcuding translation about end of promo code program according to #1465
=> Spanish transaltion updated

app/src/main/java/com/fastaccess/provider/markdown/MarkDownProvider.java
Add `.ipynb` to ARCHIVE_EXTENSIONS
=> Add .ipynb to ARCHIVE_EXTENSIONS

app/src/main/res/values-zh-rCN/strings.xml
Improved Simplified Chinese (zh-CN) translation
=> Improved Simplified Chinese (zh-CN) translation

README.md
The URL for the Project Lombok website changed. I fixed it.
=> update project lombok url

README.md
I saw in your `build.gradle` file that you use the Lottie library so I added it to the Readme.
Would be interested to know though where exactly you use the library. I mean I can't find that much animations.
=> add lottie library to readme

app/src/main/java/com/fastaccess/ui/modules/profile/overview/ProfileOverviewFragment.java, app/src/main/java/com/fastaccess/ui/widgets/AvatarLayout.java
=> reload avatar on profile's overview

app/src/main/res/values/arrays.xml
=> Word replacement (#1430)

app/src/main/java/com/fastaccess/provider/rest/RestProvider.java
Tested for compilation only. Resolves #1707
=> Add auth to all urls for download manager

app/src/main/java/com/fastaccess/ui/modules/settings/category/SettingsCategoryFragment.java
I have tried it on the debug build.  
It can successfully restore the settings now. 
Fixes #1763
=> Fix settings restore

app/src/main/res/values-ko/strings.xml
=> Update Korean strings

app/src/main/res/values-bg/strings.xml
Add missing Bulgarian language translations to `strings.xml`.
=> Add missing BG language translations
